### PR TITLE
Create ffmpeg-rebuild.py

### PR DESCRIPTION
**Pull request by leigh123linux**

### CODE REVIEW

**Comment by sergiomb2** [comment]
LGTM

**Comment by kwizart** [comment]
I don't see the point of having one script that does only one thing. (ffmpeg dependencies rebuilt).
Instead, It would be more relevant to have one script to do a rebuild from a given raw file of a list of packages (from either free/nonfree sections).
Also, this script only takes care of the free section, so there is a need to use a parameter for the nonfree one or any others that can arise.

**Comment by kwizart** [comment]
For example, the script could take a raw ffmpeg-free.txt file as a parameter.
Change the changelog to "Rebuilt for $1" and the target to f29-$2... 
(and even discover the default rawhide target using the same method used by rfpkg).

**Comment by sergiomb2** [comment]
the script it is a start , we don't have any

**Comment by kwizart** [comment]
Let's close this PR, best to only maintain one mass/ffmpeg rebuilt script to avoid any issue

**Pull request closed without merging**
